clone_depth: 2

environment:
    matrix:
#         - PYTHON: "C:\\Python37"
#           ARCH: "32"
        - PYTHON: "C:\\Python37-x64"
          ARCH: "x64"

init:

install:
    - "%PYTHON%\\python.exe --version"
    - "%PYTHON%\\Scripts\\pip install pyinstaller PyQt5 pyqt5-tools"
    # Some hack here
    - "%PYTHON%\\Scripts\\pip install git+https://github.com/n1nj4z33/sample-market-maker"
    - "%PYTHON%\\Scripts\\pyinstaller --onefile --icon=icon.ico --noconsole bmbot.py"
    - "move dist\\bmbot.exe dist\\bmbot-%ARCH%.exe"

build: off

artifacts:
    - path: "dist\\bmbot-%ARCH%.exe"

deploy:
  release: bmbot-v$(appveyor_build_version)
  description: 'Release new version'
  provider: GitHub
  auth_token:
    secure: VOVRN/x5Ulzxx+UehdUVKchl0vbb7A6NZDxQNbJHytIZmRSuP1sbGAdGP17d/wwu
  artifact: dist\bmbot-%ARCH%.exe
  draft: false
  prerelease: false
  on:
    branch: master
