language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env:
        - image=ubuntu:bionic

  install:
    - pip install -r requirements.txt
    - pyinstaller --onefile --icon=icon.ico --noconsole bmbot.py
    - move dist\bmbot dist\bmbot-linux-x64
  
script:
  - python --version

deploy:
  provider: releases
  api_key:
    secure: VOVRN/x5Ulzxx+UehdUVKchl0vbb7A6NZDxQNbJHytIZmRSuP1sbGAdGP17d/wwu
  file:
    - dist/bmbot-linux-x64
  file_glob: true
  on:
    repo: n1nj4z33/bmbot
    #tags: true
  skip_cleanup: true
