language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env:
        - image=ubuntu:bionic

  before_install:
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
  
  install: true
  
script:
  - python --version

before_deploy:
  - pyinstaller --onefile --icon=icon.ico --noconsole bmbot.py
  - move dist/bmbot dist/bmbot-linux-x64

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "dist/bmbot-linux-x64"
  file_glob: true
  on:
    repo: n1nj4z33/bmbot
    branch: master
    #tags: true
  skip_cleanup: true
